### ISSUE TITLE
CSS File Directory

### ISSUE THREAD

**Issue by oriorasajambu** [syafri-sitepu/tugas-web#5]
https://github.com/syafri-sitepu/tugas-web/blob/c70507a20960cb8d6c375ef26bdb69880c8f6a1c/public/style.css

ini file nya di letakin di `public/asset/css/style.css` biar gk error di alibaba

**Comment by syafri-sitepu** [comment]
> https://github.com/syafri-sitepu/tugas-web/blob/c70507a20960cb8d6c375ef26bdb69880c8f6a1c/public/style.css
> 
> ini file nya di letakin di `public/asset/css/style.css` biar gk error di alibaba

trus cara manggil cssnya gimana bg?
